.TH I8KCTL 1 2023-05-06 "Armin Wolf" Documentation

.SH NAME
i8kctl \- Utility for fan control on Dell notebooks

.SH SYNOPSIS
.B i8kctl [
.I options
.B ]
.br
.B i8kctl [
.I sensor
.B ] [
.I state
.B ]

.SH DESCRIPTION
.B i8kctl
is a utility to retrieve sensor information on supported Dell notebooks,
where it depends on the dell-smm-hwmon kernel module for hardware access.
.LP
When invoked without arguments it lists all available sensors and
their values.
.LP
If 'sensor' is specified and contains a valid sensor name, its reading is being displayed.
Valid sensor names are 'fan[number]' for fan sensors (fan1, fan2, ...) and 'temp[number]' for
temperature sensors (temp1, temp2, ...). If 'state' is also specified, the value of the sensor
is being set to 'state'.

.SH OPTIONS
.IP "-?, -help"
Display usage information.

.SH VERSION
.B i8kctl
needs at least linux kernel 3.0 to display temperature sensors and at
least linux kernel 5.19 to display fan sensors.

.SH NOTES
.B i8kctl
depends on the presence of the dell_smm_hwmon kernel module. If the module
is missing, all attempts to read/write sensors will fail. If the module is not
automatically loaded on your machine, then you can load it with:
.LP
.in +4n
.EX
modprobe dell_smm_hwmon ignore_dmi=1
.EE
.in
.LP
Writing sensors requires root privileges.

.SH BUGS
Invoking i8kctl on certain machines can cause significant delays which might
cause audio or input glitches. This is usually a hardware problem which can only
be fixed through a BIOS update.
.LP
Notify the maintainers of the dell_smm_hwmon kernel module if you are affected
so your model can be put on a blacklist.

.SH EXAMPLE
To set the fan state of the first fan  to '1', execute:
.LP
.in +4n
.EX
i8kctl fan1 1
.EE
.in

.SH AUTHORS
.LP
2022-2023 Armin Wolf <W_Armin@gmx.de>
.br
2013-2017 Vitor Augusto <vitorafsr@gmail.com>
.br
2001-2009 Massimo Dal Zotto <dz@debian.org>

.SH COPYRIGHT
i8kctl is part of the i8kutils package. All files are distributed under the GNU
General Public License (GPL).

.SH SEE ALSO
i8kmon(1), modprobe(8)
