#!/bin/sh

### BEGIN INIT INFO
# Provides:          i8kmon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Dell fan/cpu-temperature monitor
# Description:       Enable service provided by daemon
### END INIT INFO

# i8kmon	Dell fan/cpu-temperature monitor
#
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian GNU/Linux
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#
#		Modified for i8kutils by Karl E. Jørgensen <karl@jorgensen.com>,
#		Massimo Dal Zotto <dz@debian.org> and
#		Bradley Smith <bradsmith@debian.org>
#		Updated by Vitor Augusto <vitorafsr@gmail.com>.
#		Updated by Armin Wolf <W_Armin@gmx.de>.

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=i8kmon
DAEMON=/usr/bin/i8kmon
DESC="DELL notebook fan control"
PIDFILE=/var/run/$NAME.pid
HWMON_DEV="dell_smm"

. /lib/lsb/init-functions

case "$1" in
	start)
		test -f $DAEMON || exit 5

		log_success_msg "Starting $DESC" "$NAME"
		for ENTRY in /sys/class/hwmon/hwmon*/name
		do
			if [ $(cat $ENTRY) = $HWMON_DEV ]
			then
				start-stop-daemon --start --quiet --oknodo \
					--pidfile $PIDFILE --background --make-pidfile \
					--startas $DAEMON --chuid 0

				[ $? -eq 0 ] && exit 0

				exit 1
			fi
		done

		log_failure_msg "Could not find hwmon device ($HWMON_DEV)"
		exit 1
		;;
	stop)
		log_success_msg "Stopping $DESC" "$NAME"
		start-stop-daemon --oknodo --stop --quiet --pidfile $PIDFILE \
			--remove-pidfile

		[ $? -eq 0 ] && exit 0

		exit 1
		;;
	status)
		status_of_proc -p $PIDFILE $DAEMON $NAME
		;;
	restart|force-reload)
		$0 stop
		sleep 2
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
		exit 2
		;;
esac
